use_frameworks!
platform :ios, '11.0'

target 'DPSideMenu_Example' do
  pod 'DPSideMenu', :path => '../'

  target 'DPSideMenu_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
