use_frameworks!

target 'DPSideMenu_Example' do
  pod 'DPSideMenu', :path => '../'

  target 'DPSideMenu_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
